openapi: "3.0.3"

info:
  title: js-playground API
  version: "1.0"

paths:
  /api/v1/share:
    post:
      description: |
        This endpoint is for sharing the javascript code.
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              example: |
                console.log('Hello, World!');
      responses:
        200:
          description: success
          content:
            text/plain:
              schema:
                type: string
                example: |
                  uYvCZzbhKd6
        500:
          description: error
          content:
            text/plain:
              schema:
                type: string
                example: |
                  Internal Server Error

  /api/v1/collect/{id}:
    get:
      description: |
        This endpoint is for collecting the javascript code from id.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the code to get
      responses:
        200:
          description: success
          content:
            text/plain:
              schema:
                type: string
                example: |
                  console.log('Hello, World!');
        404:
          description: error
          content:
            text/plain:
              schema:
                type: string
                example: |
                  Not Found
        500:
          description: error
          content:
            text/plain:
              schema:
                type: string
                example: |
                  Internal Server Error

